"""Initial migration with fec_number as INT

Revision ID: b6261b80cd1d
Revises: 
Create Date: 2025-09-15 09:50:33.804146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b6261b80cd1d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('num_unity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('vehicle_plate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_index(op.f('ix_drivers_username'), 'drivers', ['username'], unique=True)
    op.create_table('salespersons',
    sa.Column('salesperson_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.PrimaryKeyConstraint('salesperson_id')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('gps_location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('salesperson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespersons.salesperson_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('fecs',
    sa.Column('fec_id', sa.Integer(), nullable=False),
    sa.Column('fec_number', sa.Integer(), nullable=False),
    sa.Column('fec_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('optimized_order_list_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('suggested_journey_polyline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('fec_id')
    )
    op.create_index(op.f('ix_fecs_fec_number'), 'fecs', ['fec_number'], unique=False)
    op.create_table('deliveries',
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('fec_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('delivery_time', sa.DateTime(), nullable=False),
    sa.Column('accepted_next_at', sa.DateTime(), nullable=False),
    sa.Column('actual_duration', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('estimated_duration', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('start_latitud', sa.Float(), nullable=False),
    sa.Column('start_longitud', sa.Float(), nullable=False),
    sa.Column('end_latitud', sa.Float(), nullable=True),
    sa.Column('end_longitud', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cancellation_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['fec_id'], ['fecs.fec_id'], ),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_index(op.f('ix_deliveries_invoice_id'), 'deliveries', ['invoice_id'], unique=False)
    op.create_table('tracking_points',
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.delivery_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_index(op.f('ix_tracking_points_timestamp'), 'tracking_points', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_points_timestamp'), table_name='tracking_points')
    op.drop_table('tracking_points')
    op.drop_index(op.f('ix_deliveries_invoice_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_fecs_fec_number'), table_name='fecs')
    op.drop_table('fecs')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('salespersons')
    op.drop_index(op.f('ix_drivers_username'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
